server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.168.13.124:9090/mark/lxy-config.git
          username: mark
          password: mark831006
          search-paths:
            - /**